id: IDE84DA7D
legacy_id: P005366
ocr_import_info:
  bdrc_scan_id: W1PD137888
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:30:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:52:57.227613+00:00'
last_modified: 2022-08-27 16:55:22.292174
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD137888
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD137888
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་བཅུ་གསུམ་པ་ཐུབ་བསྟན་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ཕུར་བུ་ལྕོག་ཡོངས་འཛིན་སྤྲུལ་སྐུ་ཐུབ་བསྟན་བྱམས་པ་ཚུལ་ཁྲིམས་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.9738311457684465
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2PD17672:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD17672
      total_pages: 527
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD17672.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9736584448785597
    legacy_id: v002
  I2PD17671:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD17671
      total_pages: 687
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD17671.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9739631184794211
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
